### ISSUE TITLE
Error with exercises and name conflict

### ISSUE THREAD

**Issue by mikeckennedy** [talkpython/reactive-web-dashboards-with-shiny-course#2]
Hey @garrettgman Can you do some a bit more clean up for us here? I appreciate the changes you've synced over from Posit. However, the github pages version that the students run exercises on the web for this course don't work and the git history is such that they can't just sync across.

For example, see:

https://talkpython.github.io/reactive-web-dashboards-with-shiny-course/exercises/2-basic-ui.html

You get this error on the problems section of basic UI 2.4

<img width="1054" alt="Screenshot 2024-07-10 at 12 27 14 PM" src="https://github.com/talkpython/reactive-web-dashboards-with-shiny-course/assets/2035561/6c7f5073-7f63-4cf7-920c-11f995a1ed59">

**Comment by garrettgman** [comment]
@mikeckennedy I'm happy to help! 

Can you help me understand the problem a little better? Did you by chance fix it? Your screenshot captures the error I attempted to fix with the PR. When I visit your link, things seem to be working. I see the fixed version below (The PR replaced `metric()` with `metric_plot()`).

<img width="1286" alt="Screenshot 2024-07-10 at 3 38 38 PM" src="https://github.com/talkpython/reactive-web-dashboards-with-shiny-course/assets/85014/4630c46e-8769-40fe-8ec0-fa71d8fb6053">

**Comment by mikeckennedy** [comment]
Thanks @garrettgman 

You know what happened? I knew of that bug and thought your PR fixed it. So I merged, then went over to check. It was still a problem. Because github pages didn't publish instantly. Looks fixed, thank you!
